name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
    # - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository != 'yym68686/uni-api'

    steps:
      - name: Check if GITHUB_TOKEN exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set"
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: yym68686/uni-api
          upstream_sync_branch: main
          target_sync_branch: main